"""Build the shipped grammar dictionary used to repair cursor-occluded OCR lines.

Usage:
    python scripts/build_grammar_seed.py [extra-lines.txt ...]

Always emits the core combat grammar for every verb the parser knows plus the
grammar learned from scripts/grammar-samples.txt (real captured lines). Each
extra file may contain raw combat lines (one per line) or per-character
template JSON saved by the app under %LOCALAPPDATA%\\DiscordOverlay\\data\\templates.
Raw lines are parsed and their actor/target names masked with ``@`` so the
output carries grammar only, never player names.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from discord_overlay.parser import COMBAT_VERBS, CombatTextParser  # noqa: E402
from discord_overlay.repair import GRAMMAR_ASSET, NAME, LineRepairer, event_names  # noqa: E402

OUTPUT = ROOT / "discord_overlay" / "assets" / GRAMMAR_ASSET
SAMPLES = ROOT / "scripts" / "grammar-samples.txt"

CORE = [
    "You {verb} @ for # points of damage",
    "You {verb} @ for # point of damage",
    "You {verb} @ with your offhand for # points of damage",
    "@ {verb} @ for # points of damage",
    "@ {verb} @ for # point of damage",
    "@ {verb} @ with their offhand for # points of damage",
    "@ {verb} YOU for # points of damage",
    "@ {verb} you for # points of damage",
    "Your pet {verb} @ for # points of damage",
    "Your pet @ {verb} @ for # points of damage",
    "Your pet @ {verb} @ with their offhand for # point of damage",
]
SPELLS_AND_HEALS = [
    "@ @ hits @ for # points of damage",
    "@ @ hits @ for # points of @ damage",
    "Your @ hits @ for # points of damage",
    "Your @ hits @ for # points of @ damage",
    "@ Damage Shield hits @ for # points of damage",
    "@ heals you for # Health",
    "@ heals @ for # Health",
    "@ @ heals you for # Health",
    "@ @ heals @ for # Health",
    "You heal @ for # Health",
    "@ restores you for # Health",
    "@ grants you # Health",
    "You try to {verb_base} @, but miss",
    "@ tries to {verb_base} you, but misses",
    "@ tries to {verb_base} @, but misses",
]


def core_lines() -> list[str]:
    verbs = [verb for verb in COMBAT_VERBS if verb.endswith("s")]
    bases = [verb for verb in COMBAT_VERBS if not verb.endswith("s")]
    lines: list[str] = []
    for pattern in CORE:
        # The game addresses the player in the second person: "You punch", "a rat bites".
        forms = bases if pattern.startswith("You ") else verbs
        lines.extend(pattern.format(verb=verb) for verb in forms)
    for pattern in SPELLS_AND_HEALS:
        if "{verb_base}" in pattern:
            lines.extend(pattern.format(verb_base=base) for base in bases)
        else:
            lines.append(pattern)
    return lines


def learned_lines(paths: list[Path]) -> list[str]:
    repairer = LineRepairer(capacity=100_000)
    parser = CombatTextParser("You")
    for path in paths:
        if path.suffix == ".json":
            repairer.load(path)
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            event = parser.parse(line)
            if event is not None and event.target != "Unknown":
                repairer.observe(line, event_names(event))
    # Only templates with every name masked are safe to ship.
    return [template for template in repairer.masked_templates() if NAME in template]


def main(argv: list[str]) -> int:
    lines = core_lines() + learned_lines([SAMPLES] + [Path(arg) for arg in argv])
    unique = sorted(set(lines), key=str.casefold)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "#! Discord Overlay grammar templates. '#' = number, '@' = actor/target/pet/spell name.\n"
        "#! Generated by scripts/build_grammar_seed.py; edit that script, not this file.\n"
        + "\n".join(unique) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(unique)} templates to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
